# Generated by Django 3.2.15 on 2023-02-02 20:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(upload_to=users.models.get_profile_pic_path),
        ),
    ]
