# Generated by Django 4.1.5 on 2023-01-27 17:29

import django.core.validators
from django.db import migrations, models
import filesapi.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SharedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(blank=True, upload_to="files")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to="images",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg"]
                            )
                        ],
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=filesapi.models.create_unique_code,
                        max_length=6,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
